### ISSUE TITLE
No background grey layer when using Dialog with the "open" prop.

### ISSUE THREAD

**Issue by remyvdwereld** [Amsterdam/design-system#1753]
There is no background grey layer when using the `open` prop. Why?

I would like to show the Dialog based on a boolean instead of using ID's en specific functions.

[codesandbox](https://codesandbox.io/p/sandbox/dialog-tlz9cj)

**Comment by dlnr** [comment]
This only seems to happen when the `open` prop value is controlled by the state, Reacts rendering somehow prevents the Dialog from using the top-layer. I've created an example where it works as advertised but Remy showed that he intends to wrap the Dialog so he can control and `onOpen` and `onClose` events. The reason is that he needs a Dialog to open (containing an `FileInput`) for each row in a table. 

So we might need `onOpen` and `onClose` props and we might also need to reconsider the `open` function because there is already a (native) `open` attribute that we control in storybook, which is confusing.

**Comment by dlnr** [comment]
Closing issue, controlling a `dialog` element in react state is not possible.
